# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  #- name: Info
  #  url: tags/
  #  weight: 20
  - name: Info
    url: info/
    weight: 30
  - name: Profile
    parent: Info
    url: info/profile/
    weight: 20
  - name: Organization
    parent: Info
    url: info/organization/
    weight: 10

  #- name: Projects
  #  url: uses/
  #  weight: 30
  - name: Projects
    url: projects/
    weight: 30
  - name: Software
    parent: Projects
    url: projects/software/
    weight: 20
  - name: Design
    parent: Projects
    url: projects/design/
    weight: 10
